### ISSUE TITLE
Great work!  Question about setting bcast & network

### ISSUE THREAD

**Issue by faddat** [kristrev/multi#11]
Okay, so:  I've got a network configured thus:

<---residential fiber--->                                    
<---residential fiber--->  All 3 go to (NAT / LB) -----(16 servers: 192.168.100.200-15 on server eth0)
<---residential fiber--->

<---slow-ass commercial fiber---> BGP Stuff ------>(16 servers: 106.53.94.200-15 on server eth1)

Of course, I'm trying to use multi.... wait as sec.... is the problem as I now suspect:  it is indeed that in /etc/network/interfaces the eth1 should come first, because it is a public address, and that I should be allowing multi to connect to eth0 as an "other" so that the public IP takes precedence?  

Presently I don't have broadcast set.  Here's my multi.yaml

eth0:
    proto: 'static'
    address: 192.168.100.202
    netmask: 255.255.255.0
    gateway: 192.168.100.1

eth1:
    proto: 'static'
    address: 103.52.94.202
    netmask: 255.255.255.0
    gateway: 103.52.94.1

/etc/network/interfaces:

# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
iface eth0 inet manual
    up ifconfig $IFACE 0.0.0.0 up
    down ifconfig $IFACE down

iface eth1 inet manual
    up ifconfig $IFACE 0.0.0.0 up
    down ifconfig $IFACE down

And BTW-- this is highly impressive code.  As this is discovered, I expect it to change some things in server-land.  Congrats!

**Comment by kristrev** [comment]
Hi,

Thanks for your comments. I am not quite sure what the problem is, but if is related to the priority of interfaces then you need to use the metric variable. Lowest metric == highest priority. Look inn ./examples for an example configuration file where this is used.

**Comment by faddat** [comment]
To the next guy-- I'm not totally sure how I got this to work, but with enough struggle, I did.
